### PR TITLE
remove helm labels from Service selector

### LINKED ISSUE #16: "release" label is not removed from Service selectors
The labels transformer removes the "chart", "release", and "heritage" labels from resources. However, it misses the [ServiceSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#servicespec-v1-core) selector.

  ```
  $ helm-convert https://kubernetes-charts.storage.googleapis.com/nginx-ingress-0.31.0.tgz
  $ cat nginx-ingress/nginx-ingress-controller-svc.yaml
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      component: controller
    name: nginx-ingress-controller
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    selector:
      app: nginx-ingress
      component: controller
      release: nginx-ingress
    type: LoadBalancer
  ```

### PR DESCRIPTION
**Pull request by ryane**
fixes #16

### CODE REVIEW

**Comment by etiennetremel** [comment]
It seems that Kustomize doesn't add common labels to `pdb.spec.selector.matchExpressions`, maybe we should think of a better way to handle such path. For example we could use a map of [kustomize GVK](https://github.com/kubernetes-sigs/kustomize/blob/v1.0.10/pkg/gvk/gvk.go) to filter resources and tell which key can be safely removed: `map[<GVK>]<path>`.

By default we should remove the one from `.metadata.labels`, but for the rest we might need that safe check, particularly for CRD where we don't really know if the labels, selector fields are used.

What do you think, does that make sense? maybe you have a better idea to handle this?

**Comment by ryane** [comment]
Not sure I totally follow, tbh. Do you have an example?

The original issue I noticed is that the `release` label is not getting removed from a Service selector. In that nginx-ingress example, you end up with a Service that does not discover any endpoints. Does this fix break something else?

**Comment by etiennetremel** [comment]
I was talking about the following conversion, when using custom resources:
```
apiVersion: custom/v1
kind: MyCustomResource
metadata:
  name: my-custom-resource
spec:
  something:
    labels: # << this shouldn't be removed but helm-convert will remove it
      someConfig: someValue
      someMoreConfig:
        labels:  ## << this should be removed
           some: label
        someMoreNestedConfig: someValue
``` 

I will work on that one, so this PR is good to go, thanks!

**Comment by etiennetremel** [comment]
created an issue for follow up: https://github.com/ContainerSolutions/helm-convert/issues/19

**Pull request merged**
